export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIE = 'GET_MOVIE'
export const MOVIE_LOADING = 'MOVIE_LOADING'
export const MOVIES_LOADING = 'MOVIES_LOADING'
export const MOVIE_NOT_FOUND = 'MOVIE_NOT_FOUND'

export const GET_TVSHOWS = 'GET_TVSHOWS'
export const GET_TVSHOW = 'GET_TVSHOW'
export const TVSHOW_LOADING = 'TVSHOW_LOADING'
export const TVSHOWS_LOADING = 'TVSHOWS_LOADING'
export const TVSHOW_NOT_FOUND = 'TVSHOW_NOT_FOUND'

export const GET_ERRORS = 'GET_ERRORS'